// <auto-generated />
using System;
using MasFinalProj.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MasFinalProj.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MasFinalProj.Domain.Models.Campaigns.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("CampaignImageId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(52)
                        .HasColumnType("nvarchar(52)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignImageId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Campaigns.Characters.Character", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CharacterImageId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(52)
                        .HasColumnType("nvarchar(52)");

                    b.Property<long?>("PlayerOwnerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CharacterImageId");

                    b.HasIndex("PlayerOwnerId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Campaigns.Characters.CharacterRelationWith", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FromCharacterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RelationValue")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<long>("ToCharacterId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ToCharacterId");

                    b.HasIndex("FromCharacterId", "ToCharacterId")
                        .IsUnique();

                    b.ToTable("CharacterRelationsWith");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Campaigns.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Campaigns.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("CampaignUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CharacterAuthorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CampaignUserId");

                    b.HasIndex("CharacterAuthorId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Campaigns.Note", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CampaignUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignUserId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ItemId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Campaigns.Stat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Campaigns.Users.CampaignUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CampaignBio")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CampaignNickname")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CampaignUserType")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("CampaignUsers");

                    b.HasDiscriminator<string>("CampaignUserType").HasValue("CampaignUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Common.Image", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Base64Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFormat")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(52)
                        .HasColumnType("nvarchar(52)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("ProfileImageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ProfileImageId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Campaigns.Users.CampaignUserGameMaster", b =>
                {
                    b.HasBaseType("MasFinalProj.Domain.Models.Campaigns.Users.CampaignUser");

                    b.HasIndex("CampaignId");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue("CampaignUserGameMaster");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Campaigns.Users.CampaignUserPlayer", b =>
                {
                    b.HasBaseType("MasFinalProj.Domain.Models.Campaigns.Users.CampaignUser");

                    b.HasIndex("CampaignId");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue("CampaignUserPlayer");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Users.Admin", b =>
                {
                    b.HasBaseType("MasFinalProj.Domain.Models.Users.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Users.Moderator", b =>
                {
                    b.HasBaseType("MasFinalProj.Domain.Models.Users.User");

                    b.Property<DateTime>("StaffSince")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Moderator");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Campaigns.Campaign", b =>
                {
                    b.HasOne("MasFinalProj.Domain.Models.Common.Image", "CampaignImage")
                        .WithMany("Campaigns")
                        .HasForeignKey("CampaignImageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CampaignImage");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Campaigns.Characters.Character", b =>
                {
                    b.HasOne("MasFinalProj.Domain.Models.Campaigns.Campaign", null)
                        .WithMany("Characters")
                        .HasForeignKey("CampaignId");

                    b.HasOne("MasFinalProj.Domain.Models.Common.Image", "CharacterImage")
                        .WithMany("Characters")
                        .HasForeignKey("CharacterImageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MasFinalProj.Domain.Models.Campaigns.Users.CampaignUserPlayer", "PlayerOwner")
                        .WithMany("ControlledCharacters")
                        .HasForeignKey("PlayerOwnerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CharacterImage");

                    b.Navigation("PlayerOwner");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Campaigns.Characters.CharacterRelationWith", b =>
                {
                    b.HasOne("MasFinalProj.Domain.Models.Campaigns.Characters.Character", "FromCharacter")
                        .WithMany("RelationsFromCharacterToOthers")
                        .HasForeignKey("FromCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MasFinalProj.Domain.Models.Campaigns.Characters.Character", "ToCharacter")
                        .WithMany("RelationsFromOthersToCharacter")
                        .HasForeignKey("ToCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromCharacter");

                    b.Navigation("ToCharacter");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Campaigns.Item", b =>
                {
                    b.HasOne("MasFinalProj.Domain.Models.Campaigns.Characters.Character", "Character")
                        .WithMany("Items")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Campaigns.Message", b =>
                {
                    b.HasOne("MasFinalProj.Domain.Models.Campaigns.Users.CampaignUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasFinalProj.Domain.Models.Campaigns.Campaign", "Campaign")
                        .WithMany("Messages")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MasFinalProj.Domain.Models.Campaigns.Users.CampaignUser", null)
                        .WithMany("Messages")
                        .HasForeignKey("CampaignUserId");

                    b.HasOne("MasFinalProj.Domain.Models.Campaigns.Characters.Character", "CharacterAuthor")
                        .WithMany()
                        .HasForeignKey("CharacterAuthorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Author");

                    b.Navigation("Campaign");

                    b.Navigation("CharacterAuthor");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Campaigns.Note", b =>
                {
                    b.HasOne("MasFinalProj.Domain.Models.Campaigns.Users.CampaignUser", "CampaignUser")
                        .WithMany("Notes")
                        .HasForeignKey("CampaignUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasFinalProj.Domain.Models.Campaigns.Characters.Character", "Character")
                        .WithMany("Notes")
                        .HasForeignKey("CharacterId");

                    b.HasOne("MasFinalProj.Domain.Models.Campaigns.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.Navigation("CampaignUser");

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Campaigns.Stat", b =>
                {
                    b.HasOne("MasFinalProj.Domain.Models.Campaigns.Characters.Character", "Character")
                        .WithMany("Stats")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Users.User", b =>
                {
                    b.HasOne("MasFinalProj.Domain.Models.Common.Image", "ProfileImage")
                        .WithMany()
                        .HasForeignKey("ProfileImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfileImage");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Campaigns.Users.CampaignUserGameMaster", b =>
                {
                    b.HasOne("MasFinalProj.Domain.Models.Campaigns.Campaign", "Campaign")
                        .WithMany("CampaignGameMaster")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasFinalProj.Domain.Models.Users.User", "User")
                        .WithMany("CampaignsAsGameMaster")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Campaigns.Users.CampaignUserPlayer", b =>
                {
                    b.HasOne("MasFinalProj.Domain.Models.Campaigns.Campaign", "Campaign")
                        .WithMany("CampaignPlayers")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasFinalProj.Domain.Models.Users.User", "User")
                        .WithMany("CampaignsAsPlayer")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Campaigns.Campaign", b =>
                {
                    b.Navigation("CampaignGameMaster");

                    b.Navigation("CampaignPlayers");

                    b.Navigation("Characters");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Campaigns.Characters.Character", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Notes");

                    b.Navigation("RelationsFromCharacterToOthers");

                    b.Navigation("RelationsFromOthersToCharacter");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Campaigns.Users.CampaignUser", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Common.Image", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("Characters");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Users.User", b =>
                {
                    b.Navigation("CampaignsAsGameMaster");

                    b.Navigation("CampaignsAsPlayer");
                });

            modelBuilder.Entity("MasFinalProj.Domain.Models.Campaigns.Users.CampaignUserPlayer", b =>
                {
                    b.Navigation("ControlledCharacters");
                });
#pragma warning restore 612, 618
        }
    }
}
